# Generated by Django 5.1 on 2024-08-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('description', models.TextField(null=True)),
                ('randomized', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['randomized'],
            },
        ),
    ]
