# Generated by Django 5.1 on 2024-08-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_images_author_images_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='images',
            name='low_res_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
