# Generated by Django 5.1 on 2024-08-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_images_options_images_low_res_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='low_res_url',
        ),
        migrations.AddField(
            model_name='images',
            name='is_published_insta',
            field=models.BooleanField(default=False),
        ),
    ]
