# Generated by Django 5.1 on 2024-08-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_images_low_res_url_images_is_published_insta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['randomized']},
        ),
        migrations.AddField(
            model_name='images',
            name='low',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
